# Shell variables
# Generated by 'wal'
wallpaper="/home/rmoses/dots/themes/purple-ascii-tree/wallpaper.png"

# Special
background='#1e1e0c'
foreground='#c6c6c2'
cursor='#c6c6c2'

# Colors
color0='#1e1e0c'
color1='#3D445A'
color2='#484C71'
color3='#553E86'
color4='#5E569B'
color5='#686EB1'
color6='#766ACB'
color7='#c6c6c2'
color8='#70705c'
color9='#3D445A'
color10='#484C71'
color11='#553E86'
color12='#5E569B'
color13='#686EB1'
color14='#766ACB'
color15='#c6c6c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
