[colors.primary]
background = "#1e1e0c"
foreground = "#c6c6c2"

[colors.cursor]
text = "#1e1e0c"
cursor = "#c6c6c2"

[colors.vi_mode_cursor]
text = "#1e1e0c"
cursor = "#c6c6c2"

[colors.search.matches]
foreground = "#1e1e0c"
background = "#c6c6c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#70705c"
background = "#c6c6c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1e1e0c"
red = "#3D445A"
green = "#484C71"
yellow = "#553E86"
blue = "#5E569B"
magenta = "#686EB1"
cyan = "#766ACB"
white = "#c6c6c2"

[colors.bright]
black = "#70705c"
red = "#3D445A"
green = "#484C71"
yellow = "#553E86"
blue = "#5E569B"
magenta = "#686EB1"
cyan = "#766ACB"
white = "#c6c6c2"

[colors.dim]
black = "#c6c6c2"
red = "#3D445A"
green = "#686EB1"
yellow = "#553E86"
blue = "#5E569B"
magenta = "#484C71"
cyan = "#766ACB"
white = "#70705c"

