--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rmoses/dots/themes/purple-ascii-tree/wallpaper.png"

-- Special
background="#1e1e0c"
foreground="#c6c6c2"
cursor="#c6c6c2"

-- Colors
color0="#1e1e0c"
color1="#3D445A"
color2="#484C71"
color3="#553E86"
color4="#5E569B"
color5="#686EB1"
color6="#766ACB"
color7="#c6c6c2"
color8="#70705c"
color9="#3D445A"
color10="#484C71"
color11="#553E86"
color12="#5E569B"
color13="#686EB1"
color14="#766ACB"
color15="#c6c6c2"
