[colors]
background = '#1e1e0c8e'
black = '#1e1e0c'
blue = '#3D445A'
cursor = '#c6c6c2'
cyan = '#484C71'
foreground = '#c6c6c2'
green = '#553E86'
magenta = '#5E569B'
red = '#686EB1'
tabs = '#c6c6c2'
tabs-active = '#766ACB'
white = '#c6c6c2'
yellow = '#c6c6c2'
dim-black = '#1e1e0c8e'
dim-blue = '#3D445A8e'
dim-cyan = '#484C718e'
dim-foreground = '#c6c6c28e'
dim-green = '#553E868e'
dim-magenta = '#5E569B8e'
dim-red = '#686EB18e'
dim-white = '#766ACB8e'
dim-yellow = '#c6c6c28e'
light-black = '#3D445A'
light-blue = '#484C71'
light-cyan = '#553E86'
light-foreground = '#5E569B'
light-green = '#686EB1'
light-magenta = '#766ACB'
light-red = '#c6c6c2'
light-white = '#3D445A'
light-yellow = '#484C71'
