[config]

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-kitty.conf'

#[templates.cava]
#input_path = 'templates/cava-colors.ini'
#output_path = '~/.config/cava/themes/main'
#post_hook = "pkill -USR1 cava"

#[templates.pywalfox]
#input_path = 'templates/pywalfox-colors'
#output_path = '~/.cache/wal/colors.json'
#post_hook = 'pywalfox update'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
