theme = "dracula"

[editor]
line-number = "relative"
bufferline = "always"
[editor.cursor-shape]
insert = "bar"

[editor.statusline]
center = ["mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
